/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-09-11 08:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.recommend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/GoodCard/eclipse-work/wtpwebapps/GoodCard/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.9.RELEASE.jar", Long.valueOf(1503897389200L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1503897430255L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/GoodCard/eclipse-work/wtpwebapps/GoodCard/WEB-INF/lib/spring-webmvc-4.3.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1496830342000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/bootstrap/css/bootstrap.min.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/css/main.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/css/topMenu.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/css/cleardiv.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/font-awesome/css/font-awesome.min.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/css/clean-blog.min.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/css/main.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/css/pollForm.css?ver=2\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Script File -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/js/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/custom/js/poll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function getAgeFromBirthDay(birth_day) {\r\n");
      out.write("\r\n");
      out.write("\t// 전달받은 생년월일로 Date 객체 생성한다. 이하 생년월일 객체라고 칭한다.\r\n");
      out.write("\tvar birthday = new Date(birth_day);\r\n");
      out.write("\r\n");
      out.write("\t// 오늘 날짜 기준으로 나이를 구하기 위해 Date 객체 생성한다. -> 이하 오늘날짜 객체라고 칭한다.\r\n");
      out.write("\tvar today = new Date();\r\n");
      out.write("\r\n");
      out.write("\t// 오늘날짜 객체의 연도에서 생년월일 객체의 연도를 뺀다.\r\n");
      out.write("\tvar years = today.getFullYear() - birthday.getFullYear();\r\n");
      out.write("\r\n");
      out.write("\t// years 의 값이 실질적으로 구해진 나이이다.\r\n");
      out.write("\t\r\n");
      out.write("\t/*\r\n");
      out.write("\t* 계속해서 만 나이 계산을 원하면 아래 처리를 계속해준다.\r\n");
      out.write("\t* 연도가 같은 두 객체를 비교하여 생년월일 객체가 오늘 날짜 객체보다 크다면 -1 해준다. \r\n");
      out.write("\t* (생일이 아직 지나지 않았다면 -1 을 한다.)\r\n");
      out.write("\t*/\r\n");
      out.write("\t// 생년월일 객체의 연도를 오늘 날짜 객체의 연도로 변경\r\n");
      out.write("\tbirthday.setFullYear(today.getFullYear());\r\n");
      out.write("\r\n");
      out.write("\t// 같은 연도가 된 객체를 비교하여 월일이 지났는 지 여부를 판단하여 years 를 뺀다.\r\n");
      out.write("\tif (today < birthday) years--;\r\n");
      out.write("\t\r\n");
      out.write("\treturn years;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkForm(){\r\n");
      out.write("\tvar inputAmount = $('#inputAmount').val();\r\n");
      out.write("\tvar inputAge = $('#input_age').val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(isNaN(parseInt(inputAmount))){\r\n");
      out.write("\t\t$('#inputAmount').focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(!$('input:radio[name=cardType]').is(':checked')){\r\n");
      out.write("\t\t$('div_cardType_radio').css(\"background\", \"#E5E5E5\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(isNaN(parseInt(inputAge))){\r\n");
      out.write("\t\t$('#input_age').focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\t\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar birth_day = $('#birth_date').val();\r\n");
      out.write("\t\t$('#input_login_age').val(getAgeFromBirthDay(birth_day));\r\n");
      out.write("\r\n");
      out.write("\t\t$('#submitPoll').click(function() {\r\n");
      out.write("\t\t\t$('div_cardType_radio').css(\"background-color\", \"\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 필수 항목 입력되었는지 확인\r\n");
      out.write("\t\t\tif (!checkForm()) {\r\n");
      out.write("\t\t\t\talert('필수 항목을 작성하세요.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 입력되지 않은 항목 0으로 셋팅\t\t\t\r\n");
      out.write("\t\t\tvar lists = $('#pollForm').find('input');\r\n");
      out.write("\t\t\tvar result = 0;\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (var i = 0; i < lists.length - 1; i++) {\r\n");
      out.write("\t\t\t\tif (isNaN(parseInt($(lists[i]).val()))) {\r\n");
      out.write("\t\t\t\t\t$(lists[i]).val(0);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/* 인풋 */\r\n");
      out.write("input[type=radio] {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tpadding: 0 20px;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, 0.08);\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\t-webkit-transition: all 0.3s ease-out;\r\n");
      out.write("\t-moz-transition: all 0.3s ease-out;\r\n");
      out.write("\t-ms-transition: all 0.3s ease-out;\r\n");
      out.write("\t-o-transition: all 0.3s ease-out;\r\n");
      out.write("\ttransition: all 0.3s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-label i {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\t-webkit-transition: opacity 0.3s ease-out;\r\n");
      out.write("\t-moz-transition: opacity 0.3s ease-out;\r\n");
      out.write("\t-ms-transition: opacity 0.3s ease-out;\r\n");
      out.write("\t-o-transition: opacity 0.3s ease-out;\r\n");
      out.write("\ttransition: opacity 0.3s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio:checked+.radio-label {\r\n");
      out.write("\tbackground: rgba(4, 120, 193, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio:checked+.radio-label i {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio+.radio-label span {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\t-webkit-transition: all 0.3s ease-out;\r\n");
      out.write("\t-moz-transition: all 0.3s ease-out;\r\n");
      out.write("\t-ms-transition: all 0.3s ease-out;\r\n");
      out.write("\t-o-transition: all 0.3s ease-out;\r\n");
      out.write("\ttransition: all 0.3s ease-out;\r\n");
      out.write("\t-webkit-transform: translateX(-13px);\r\n");
      out.write("\t-moz-transform: translateX(-13px);\r\n");
      out.write("\t-ms-transform: translateX(-13px);\r\n");
      out.write("\t-o-transform: translateX(-13px);\r\n");
      out.write("\ttransform: translateX(-13px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio:checked+.radio-label span {\r\n");
      out.write("\t-webkit-transform: translateX(0);\r\n");
      out.write("\t-moz-transform: translateX(0);\r\n");
      out.write("\t-ms-transform: translateX(0);\r\n");
      out.write("\t-o-transform: translateX(0);\r\n");
      out.write("\ttransform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit_button {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tfont-family: 'Noto Sans KR', serif;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".go_main {\r\n");
      out.write("\tborder: 1px solid #333;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tfont-family: 'Noto Sans KR', serif;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<hr style=\"margin-top: 0px; margin-bottom: 5px; clear: both;\">\r\n");
      out.write("\t<div id=\"subMenu\" class=\"container\">\r\n");
      out.write("\t\t<i class=\"fa fa-home\" aria-hidden=\"true\"></i> &nbsp;홈&nbsp;>&nbsp;내게\r\n");
      out.write("\t\t맞는 카드 찾기&nbsp;>&nbsp;설문조사\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"margin-bottom: 0px; margin-top: 5px; clear: both;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"poll-main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<section class=\"section-wrapper\"\r\n");
      out.write("\t\t\tstyle=\"padding-top: 100px; padding-bottom: 100px;\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div id=\"poll_title\" class=\"row\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin: 0px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<b>설문조사</b>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"color: gray;\">\r\n");
      out.write("\t\t\t\t\t개인별 맞춤 서비스를 제공하기 위한 사전 설문조사입니다.<br> 한 달 평균 소비 패턴을 입력하시면, 분석 후\r\n");
      out.write("\t\t\t\t\t회원님께 최적의 카드를 추천해드립니다. <br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"height: 30px; clear: both;\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"width: 100%; color: red;\">\r\n");
      out.write("\t\t\t\t\t* 필수 입력 항목입니다. 빠짐없이 입력해주세요.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"height: 30px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"pollForm\" method=\"post\"\r\n");
      out.write("\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/recommend/poll.do\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"div_cardType_radio\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-credit-card-alt\" aria-hidden=\"true\"></i>&nbsp;카드 유형&nbsp;<i style=\"color:red;\">*</i>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input name=\"cardType\" type=\"radio\"\tid=\"radio0\" class=\"radio\" value=\"credit\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"radio0\" class=\"radio-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>신용카드</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input name=\"cardType\" type=\"radio\" id=\"radio1\" class=\"radio\" value=\"check\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"radio1\" class=\"radio-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>체크카드</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</span>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- age -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-info\" aria-hidden=\"true\"></i>&nbsp;나이&nbsp;<i style=\"color:red;\">*</i>\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp;만\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon \"> <i>￦</i>&nbsp;월 예산&nbsp;<i style=\"color:red;\">*</i>\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputAmount\" name=\"amount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- transportation -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-bus\"></i>&nbsp;대중교통\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputTransportation\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"transportationAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- SmartPhone -->\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-mobile\"></i>&nbsp;통신 요금 </span>&nbsp; <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputCommunication\" name=\"communicationAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원 <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tid=\"detail_button_communication\">상세보기&nbsp;▼</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tid=\"hide_button_communication\" style=\"display: none;\">접기&nbsp;▲</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- detail smartPhone -->\r\n");
      out.write("\t\t\t\t\t<div id=\"display_detail_communication\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"display-communication-list\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 70px; margin-bottom: 70px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"display-ul\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-communication-li\"><b>SKT</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputCommunicationSkt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"communicationSkt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-communication-li', '#inputCommunication')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-communication-li\"><b>KT</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputCommunicationKt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"communicationKt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-communication-li', '#inputCommunication')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-communication-li\"><b>LG U+</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputCommunicationUPlus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"communicationUPlus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-communication-li', '#inputCommunication')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-communication-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>기타</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputCommunicationEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"communicationEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-communication-li', '#inputCommunication')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- gasStation -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"><i class=\"fa fa-car\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> &nbsp;주유소 </span>&nbsp; <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputGasStation\" name=\"gasStationAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- movie -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-video-camera\" aria-hidden=\"true\"></i> &nbsp;영화관\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputMovie\" name=\"movieAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- cafeBakery -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-coffee\" aria-hidden=\"true\"></i>&nbsp;카페\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputCafeBakery\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"cafeBakeryAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원 <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\"> <span id=\"detail_button_cafeBakery\">상세보기&nbsp;▼</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"hide_button_cafeBakery\" style=\"display: none;\">접기&nbsp;▲</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- detail cafeBakery -->\r\n");
      out.write("\t\t\t\t\t<div id=\"display_detail_cafeBakery\" class=\"display-cafeBakery-list\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 70px; margin-bottom: 70px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"display-ul\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"><b>스타벅스</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputStarbucks\" name=\"starbucks\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"><b>투썸플레이스</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputTwosomePlace\" name=\"twosomePlace\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"><b>카페베네</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputCafebene\" name=\"cafebene\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"><b>엔젤리너스</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputAngelinus\" name=\"angelinus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"><b>커피빈</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputCoffebean\" name=\"coffebean\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>이디야</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputEdiya\" name=\"ediya\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>할리스</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputHollys\" name=\"hollys\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>배스킨라빈스</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputBaskinRobbins\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"baskinRobbins\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>던킨도너츠</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputDunkinDonuts\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"dunkinDonuts\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>파스쿠찌</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputPascucci\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"pascucci\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>탐앤탐스</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputTomNToms\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tomNToms\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>스무디킹</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputSmoothieKing\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"smoothieKing\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>파리바게트</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputParisBaguette\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"parisBaguette\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>뚜레쥬르</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputTousLesJours\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"hollys\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-cafeBakery-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>기타</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputCafeBakeryEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"cafeBakeryEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-cafeBakery-li', '#inputCafeBakery')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"cafeBakery_margin\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 60px; clear: both; display: none;\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- restaurant -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-cutlery\" aria-hidden=\"true\"></i> &nbsp;패밀리 레스토랑 </span>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"inputRestaurant\" name=\"restaurantAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원 <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\"> <span id=\"detail_button_restaurant\">상세보기&nbsp;▼</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"hide_button_restaurant\" style=\"display: none;\">접기&nbsp;▲</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- detail restaurant -->\r\n");
      out.write("\t\t\t\t\t<div id=\"display_detail_restaurant\" class=\"display-restaurant-list\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 70px; margin-bottom: 70px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"display-ul\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"><b>아웃백</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputOutback\" name=\"outback\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"><b>VIPS</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputVips\" name=\"vips\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"><b>애슐리</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputAshley\" name=\"ashley\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"><b>T.G.I. Friday's</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputTgif\" name=\"tgif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"><b>매드포갈릭</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputMadForGarlic\" name=\"madForGarlic\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-restaurant-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>기타</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputRestaurantEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"restaurantEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-restaurant-li', '#inputRestaurant')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- fastFood -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"><i>F</i> &nbsp;패스트푸드</span>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"inputFastFood\" name=\"fastFoodAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원 <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\"> <span id=\"detail_button_fastFood\">상세보기&nbsp;▼</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"hide_button_fastFood\" style=\"display: none;\">접기&nbsp;▲</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- detail fastFood -->\r\n");
      out.write("\t\t\t\t\t<div id=\"display_detail_fastFood\" class=\"display-fastFood-list\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-top: 70px; margin-bottom: 70px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"display-ul\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>맥도날드</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputMcDonalds\" name=\"mcDonalds\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>롯데리아</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputLotteRia\" name=\"lotteRia\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>버거킹</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputBurgurKing\" name=\"burgurKing\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>KFC</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputKfc\" name=\"kfc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>미스터피자</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputMrPizza\" name=\"mrPizza\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>도미노피자</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputDominoPizza\" name=\"dominoPizza\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>피자헛</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputPizzaHut\" name=\"pizzaHut\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"><b>파파존스</b><br> <span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputPapaJohns\" name=\"papaJohns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"display-fastFood-li\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-right: 1px solid #E0E0E0;\"><b>기타</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"text\" id=\"inputfastFoodEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"fastFoodEtc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 25%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocusout=\"sumValue('.display-fastFood-li', '#inputFastFood')\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t\t\t</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"fastFood_margin\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 60px; clear: both; display: none;\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- cafeTeria -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-beer\" aria-hidden=\"true\"></i>&nbsp;식당/주점</span>&nbsp; <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" id=\"inputCafeteria\" name=\"cafeteriaAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- convenience -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-clock-o\" aria-hidden=\"true\"></i> &nbsp;편의점\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputConvenience\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"convenienceAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- mart -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i> &nbsp;대형마트\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputMart\" name=\"martAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- superMarket -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-shopping-basket\" aria-hidden=\"true\"></i> &nbsp;슈퍼마켓\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputSuperMarket\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"superMarketAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Online-Shopping -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-globe\" aria-hidden=\"true\"></i> &nbsp;온라인쇼핑\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputOnlineShopping\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"onlineShoppingAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Beauty -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-opera\" aria-hidden=\"true\"></i> &nbsp;드럭스토어\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputBeauty\" name=\"beautyAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- AmusementPark -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-clock-o\" aria-hidden=\"true\"></i> &nbsp;놀이공원\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputAmusementPark\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"amusementParkAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Academy -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-pencil\" aria-hidden=\"true\"></i> &nbsp;학원\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputAcademy\" name=\"academyAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- BookStore -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-book\" aria-hidden=\"true\"></i> &nbsp;서점\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputBookstore\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"bookstoreAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 10px; clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Medical -->\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"custom-input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-medkit\" aria-hidden=\"true\"></i> &nbsp;의료서비스\r\n");
      out.write("\t\t\t\t\t\t</span>&nbsp; <input type=\"text\" id=\"inputMedical\" name=\"medicalAmount\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 5%\"\r\n");
      out.write("\t\t\t\t\t\t\tonkeydown=\"onlyNumber(this)\">&nbsp;만원\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 70px; clear: both;\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"submitPoll\" class=\"submit_button\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"설문조사 완료\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"goMain\" class=\"go_main\">메인 페이지</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \t\t<div style=\"width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"submitPoll\" class=\"submit_button\">설문조사 완료</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"goMain\" class=\"go_main\">메인 페이지</button>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/popper/popper.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for this template -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/clean-blog.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/recommend/pollForm.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("context");
      // /WEB-INF/jsp/recommend/pollForm.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/recommend/pollForm.jsp(12,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/recommend/pollForm.jsp(285,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<input id=\"birth_date\" type=\"hidden\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.birthDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t<input id=\"input_login_age\" type=\"text\" name=\"age\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 3%; margin-right: 5px;\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"> 세\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<input id=\"input_age\" type=\"text\" name=\"age\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 0px; border-bottom: 1px solid black; width: 3%; margin-right: 5px;\"> 세\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
